Fs
pkivolowitz/pas pull request #19
Opened 2017-04-20 03:44 UTC by pkivolowitz

Ignore the April 17 commits - they won't survive.

2017-04-20 15:07 UTC, LOZORD requested changes
Everything looks pretty good, though a few fixes/discussions are required. Work has trained me to be picky about a few things...

2017-04-20 15:07 UTC, LOZORD commented on .gitignore
> +# Generated proto files
If you are going to gitignore these files, we should put together a script or something that makes the generation seamless for a fresh `git clone` (especially thinking of [CI](https://en.wikipedia.org/wiki/Continuous_integration)).

I much prefer to have an "install and build" script than committing the generated files.

2017-04-20 15:07 UTC, LOZORD commented on client/client.cpp
> +	sc.set_device_id(99);
Can this be some "unknown" proto value instead? Not a fan of magic numbers.

2017-04-20 15:07 UTC, LOZORD commented on client/client.cpp
> +			cout << o.value() << endl;
Should this (and below) be a log instead?

2017-04-20 15:07 UTC, LOZORD commented on client/client.cpp
> +			if (l == "baddac")
Should this be a switch statement? Up to you.

2017-04-20 15:07 UTC, LOZORD commented on fsdev/fsmain.cpp
> +// Experimenting with new indentation style - I haven't changed in 40 years. Change is good.
What is the new style? :fearful:

2017-04-20 15:07 UTC, LOZORD commented on fsdev/fsmain.cpp
> +bool ParseOptions(int argc, char * argv[], bool & real_db, string & path, string & nspace, bool & do_checksum_analysis)
Instead of mutating arguments, maybe return a struct of representing parsed args?
Or better yet, play with another [Google toy](https://github.com/gflags/gflags).

2017-04-20 15:07 UTC, LOZORD commented on fsdev/fsmain.cpp
> +			string command_line = "md5sum -b \"" + path + "\"";
We should probably be using a hashing package instead of running a command...

2017-04-20 15:07 UTC, LOZORD commented on protos/commands.proto
> +	PLAY_TRACK_DEVICE = 1;			//	TwoIntegers
Fix indent alignment (here and below)?

2017-04-20 15:07 UTC, LOZORD commented on fsdev/fsmain.cpp
> +		LOG(_log_, "");
Does this line have a use?

2017-04-20 15:07 UTC, LOZORD commented on protos/commands.proto
> +	uint64 value_a = 2;
Could you make these names more useful? No need to be __too__ generic. What you have with `TwoStrings` is good, however I would also rename `TwoString` to be more useful, like `DatabaseQueryPair` or something.

I prefer fluency/useful naming over generic-ness.

2017-04-20 15:07 UTC, LOZORD commented on server/connection_manager.cpp
> +				// If it should come to pass that there is both a DB error
Sure, that's fine with me... "Should never happen" :stuck_out_tongue_winking_eye:

2017-04-20 15:07 UTC, LOZORD commented on server/connection_manager.cpp
> +				else if ((int) o.value_a() < ndacs && acs[o.value_a()] != nullptr &&
Maybe refactor into a function? This is a lot to comprehend in an if statement.

2017-04-20 15:57 UTC, pkivolowitz commented
The indentation issues you see are being introduced by the web or using
different editors. Things are always indented well as I edit. I am not sure
if we can do anything to prevent this.

---
I totally agree with specific useful naming. However, on the generic naming
of new protos, any specificity would be wrong in some normal / frequently
occurring case.

For example, OneInteger's value might be a device index or it might be the
number of artists or the number of tracks or...

This is why I went away from specific names of protos (but keep the
specific values of type as defined in the Type enum). Do you think there is
a better way?
---

I can definitely remove the 99. Good suggestion.
---

On using more Google / Anyone's packages here are my thoughts:
- The more dependencies we introduce, the harder it is to build. I hate
that about Linux. Get this, then that, then that and that and that and
that. Patch that with this but that's not maintained anymore so get this
patch of the patch from that. And so one.
- What happens when these things go out of style, are changed in a
non-backwards compatible way or simply disappear?

I really like the proto buffers but by itself it makes building much
harder. It takes an hour to build from source which you have to because
there seems to be no easy installer. And, you need to remove the old v2
that comes with Ubuntu. And you need go. You see what I mean?

It's like javascript framework salad.  I hate that. What are your thoughts?
---

LOG(_log_, "") do have use. They get generated as verbose... so won't show
up. If they do, it tells you you definitively got to line ____. This is
used when you want to know you got somewhere to see the flow of execution.
It tells the story of the code in the log. The necessary data is already
contained in the __FUNCTION__ and __LINE__  - not other text is needed.
---

I am struggling with .gitignore - I could use help making it ignore the
generated files. The obvious things I've tried on commands.pb.* haven't
worked.



On Thu, Apr 20, 2017 at 10:07 AM, Leo Rudberg <notifications@github.com>
wrote:

> *@LOZORD* requested changes on this pull request.
>
> Everything looks pretty good, though a few fixes/discussions are required.
> Work has trained me to be picky about a few things...
> ------------------------------
>
> In .gitignore
> <https://github.com/pkivolowitz/pas/pull/19#discussion_r112469443>:
>
> > @@ -44,3 +44,8 @@ fsmain
>  # Text files
>  play*.txt
>
> +# Generated proto files
>
> If you are going to gitignore these files, we should put together a script
> or something that makes the generation seamless for a fresh git clone
> (especially thinking of CI
> <https://en.wikipedia.org/wiki/Continuous_integration>).
>
> I much prefer to have an "install and build" script than committing the
> generated files.
> ------------------------------
>
> In client/client.cpp
> <https://github.com/pkivolowitz/pas/pull/19#discussion_r112469743>:
>
> > @@ -587,6 +588,43 @@ void DevCmdForOneString(Type type, int server_socket)
>  	}
>  }
>
> +void BadDAC(int server_socket)
> +{
> +	string s;
> +	WhatDeviceCommand sc;
> +	sc.set_type(WHO_DEVICE);
> +	sc.set_device_id(99);
>
> Can this be some "unknown" proto value instead? Not a fan of magic numbers.
> ------------------------------
>
> In client/client.cpp
> <https://github.com/pkivolowitz/pas/pull/19#discussion_r112469989>:
>
> > +	string s;
> +	WhatDeviceCommand sc;
> +	sc.set_type(WHO_DEVICE);
> +	sc.set_device_id(99);
> +	bool outcome = sc.SerializeToString(&s);
> +	if (!outcome)
> +		throw string("bad serialize");
> +	SendPB(s, server_socket);
> +	Type type;
> +	s = GetResponse(server_socket, type);
> +	if (type == Type::ONE_STRING)
> +	{
> +		OneString o;
> +		if (o.ParseFromString(s))
> +		{
> +			cout << o.value() << endl;
>
> Should this (and below) be a log instead?
> ------------------------------
>
> In client/client.cpp
> <https://github.com/pkivolowitz/pas/pull/19#discussion_r112470528>:
>
> > @@ -749,6 +815,10 @@ int main(int argc, char * argv[])
>  			cout << "Command: ";
>  			getline(cin, l);
>
> +			if (l == "baddac")
>
> Should this be a switch statement? Up to you.
> ------------------------------
>
> In fsdev/fsmain.cpp
> <https://github.com/pkivolowitz/pas/pull/19#discussion_r112470927>:
>
> >  #include "fs.h"
>
>  using namespace std;
>  using namespace pas;
>
>  Logger _log_("/tmp/fslog.txt", LogLevel::MINIMAL);
>
> -bool ParseOptions(int argc, char * argv[], bool & real_db, string & path, string & nspace)
> +extern const int BSIZE;
> +
> +// Experimenting with new indentation style - I haven't changed in 40 years. Change is good.
>
> What is the new style? 😨
> ------------------------------
>
> In fsdev/fsmain.cpp
> <https://github.com/pkivolowitz/pas/pull/19#discussion_r112471971>:
>
> >  #include "fs.h"
>
>  using namespace std;
>  using namespace pas;
>
>  Logger _log_("/tmp/fslog.txt", LogLevel::MINIMAL);
>
> -bool ParseOptions(int argc, char * argv[], bool & real_db, string & path, string & nspace)
> +extern const int BSIZE;
> +
> +// Experimenting with new indentation style - I haven't changed in 40 years. Change is good.
> +
> +bool ParseOptions(int argc, char * argv[], bool & real_db, string & path, string & nspace, bool & do_checksum_analysis)
>
> Instead of mutating arguments, maybe return a struct of representing
> parsed args?
> Or better yet, play with another Google toy
> <https://github.com/gflags/gflags>.
> ------------------------------
>
> In fsdev/fsmain.cpp
> <https://github.com/pkivolowitz/pas/pull/19#discussion_r112472289>:
>
> >  				continue;
> -			cerr << p << endl;
> +			string command_line = "md5sum -b \"" + path + "\"";
>
> We should probably be using a hashing package instead of running a
> command...
> ------------------------------
>
> In protos/commands.proto
> <https://github.com/pkivolowitz/pas/pull/19#discussion_r112472830>:
>
> > -	DAC_INFO_COMMAND = 19;
> -	NEXT_DEVICE = 20;
> -	COPY_QUEUE = 21;
> -	MOVE_QUEUE = 22;
> -	APPEND_QUEUE = 23;
> -	LOG_LEVEL = 24;
> -	LOG_LEVEL_QUERY = 25;
> -}
> -
> -// This is a return type
> +	//
> +	// ENUM value 					CAN BE IMPLEMENTED BY:
> +	//
> +
> +	GENERIC = 0;					//	-na-
> +	PLAY_TRACK_DEVICE = 1;			//	TwoIntegers
>
> Fix indent alignment (here and below)?
> ------------------------------
>
> In fsdev/fsmain.cpp
> <https://github.com/pkivolowitz/pas/pull/19#discussion_r112473456>:
>
> > +	vector<DIRENT> t;
> +	vector<string> valid_extensions { "mp3", "flac", "wav", "m4a", "ogg" };
> +	bool do_db = false;
> +	string root;
> +	string nspace;
> +	bool do_checksum_analysis = false;
> +
> +	LOG(_log_, "");
> +	try {
> +		if (ParseOptions(argc, argv, do_db, root, nspace, do_checksum_analysis)) {
> +			if (*(root.end() - 1) == '/')
> +				root.erase(root.end() - 1);
> +
> +			Discover(root, valid_extensions, t, -1, zero, true, _log_);
> +		}
> +		LOG(_log_, "");
>
> Does this line have a use?
> ------------------------------
>
> In protos/commands.proto
> <https://github.com/pkivolowitz/pas/pull/19#discussion_r112473900>:
>
> > +	uint64 value = 2;
> +}
> +
> +message OneString {
> +	Type type = 1;
> +	string value = 2;
> +}
> +
> +message OneFloat {
> +	Type type = 1;
> +	float value = 2;
> +}
> +
> +message TwoIntegers {
> +	Type type = 1;
> +	uint64 value_a = 2;
>
> Could you make these names more useful? No need to be *too* generic. What
> you have with TwoStrings is good, however I would also rename TwoString
> to be more useful, like DatabaseQueryPair or something.
>
> I prefer fluency/useful naming over generic-ness.
> ------------------------------
>
> In server/connection_manager.cpp
> <https://github.com/pkivolowitz/pas/pull/19#discussion_r112477087>:
>
> >  				LOG2(_log_, nullptr, VERBOSE);
>  				SendPB(s, socket);
>  			}
>  			break;
>
>  			case Type::TRACK_COUNT:
>  			{
> +				// If it should come to pass that there is both a DB error
>
> Sure, that's fine with me... "Should never happen" 😜
> ------------------------------
> [...]

2017-04-20 15:59 UTC, pkivolowitz commented on .gitignore
> +# Generated proto files
OH - this is how you reply! Please see email - I'll use this in the future.

2017-04-20 16:30 UTC, LOZORD commented
Responding in order of your comments:

1. We should adopt a standard formatter for all languages we use. [Here's a good one.](https://clang.llvm.org/docs/ClangFormat.html)

2. I would prefer something like:

```proto
message DeviceInfo {
  int32 device_index = 1;
}

message ArtistInfo {
  int32 artist_count = 1;
}
```

3. As long as we test our own stuff, I'm fine not using packages, but if we don't want to add tests, packages are the best way to "deal with less code". I would say using packages is hard in the short term because dev work has to deal with infrastructure setup instead of new features, but it is worth it in the long term.

4.  I was _raised_ by the JavaScript framework salad. As above, we would need to work on install infra (definitely not easy), but it is worth it in the long term. Up to you, but we might be adding tech debt :confused: 

5. Ok, fine keeping the log then.

6. You might to use specify the protos directory. Otherwise, we should create a `generated` directory that we can ignore entirely.

Please let me know if you need anything else clarified.

2017-04-20 16:55 UTC, pkivolowitz commented
I don't want to be stuck in the past. Working with you is a chance for me
to learn new things.

So, I'll make this proposal...

1. We pause on new development.

2. I will concentrate on documentation and commenting.

3. Can you work on the "infra" to make build / install a one / two or three
step process?

If I can take a virgin Ubuntu-based distro and enter one or two or even
three commands in bash and get everything installed and ready to build, I
would be willing to try all / most of the new stuff you desire.

Maybe take a week or two or three? Would you be willing to do that and is
that enough time?

Unless others can make use of our stuff, our stuff isn't that useful so I
am on board if we can make it easy to install the development requirements.



On Thu, Apr 20, 2017 at 11:30 AM, Leo Rudberg <notifications@github.com>
wrote:

> Responding in order of your comments:
>
>    1.
>
>    We should adopt a standard formatter for all languages we use. Here's
>    a good one. <https://clang.llvm.org/docs/ClangFormat.html>
>    2.
>
>    I would prefer something like:
>
> message DeviceInfo {
>   int32 device_index = 1;
> }
> message ArtistInfo {
>   int32 artist_count = 1;
> }
>
>
>    1.
>
>    As long as we test our own stuff, I'm fine not using packages, but if
>    we don't want to add tests, packages are the best way to "deal with less
>    code". I would say using packages is hard in the short term because dev
>    work has to deal with infrastructure setup instead of new features, but it
>    is worth it in the long term.
>    2.
>
>    I was *raised* by the JavaScript framework salad. As above, we would
>    need to work on install infra (definitely not easy), but it is worth it in
>    the long term. Up to you, but we might be adding tech debt 😕
>    3.
>
>    Ok, fine keeping the log then.
>    4.
>
>    You might to use specify the protos directory. Otherwise, we should
>    create a generated directory that we can ignore entirely.
>
> Please let me know if you need anything else clarified.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pkivolowitz/pas/pull/19#issuecomment-295802733>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AD5TQyDVkNkxDuPepJJJTshUqMC3TgFrks5rx4gPgaJpZM4NCgUx>
> .
>

2017-04-21 02:16 UTC, pkivolowitz commented
This is reopened after fixing the repo.

2017-04-22 02:55 UTC, closed without merging